### ISSUE TITLE
Create new structure

### ISSUE THREAD

**Issue by robjullian** [coldwireorg/bloc#19]
While making the file sharing system, I noticed that the current file structure is bad and makes impossible to safely share files.
In addition to this problem, we recently moved to MongoDB, which is a problem because it makes harder to link tables between each others.

In order to fix this, we will create a whole new structure of files, this means rewriting the models for SQL and implementing PostgreSQL.

This is a *dirty and bad* graph of the relations between the tables in the database:
![db](https://user-images.githubusercontent.com/19715481/145244176-ce666c43-ad32-46e3-b8c2-1b75892025f1.jpg)

**Comment by robjullian** [comment]
The graph is wrong obviously, but yes we managed to have a new SQL structure, at least we have added the new database system to the Auth controllers. Now looking forward to put it in all the others controllers and to finally implement the file sharing feature

**Comment by PowerSaucisse** [comment]
Hey! 
You can load SQL script to generate automatic diagram here : https://dbdiagram.io/

![image](https://user-images.githubusercontent.com/64791937/145406719-8d500215-101d-4dcd-9d1b-9f7ef534fac0.png)

**Comment by robjullian** [comment]
Thanks ! @PowerSaucisse

**Comment by robjullian** [comment]
Everything is done here, will probably need to fix some bugs later, but basically everything is working!
